<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Fitting Exercise – Esther Palmer Data Analysis Portfolio</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2fee8176d83b8b83b3f52c1bb3497846.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Esther Palmer Data Analysis Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../aboutme.html"> 
<span class="menu-text">About Me</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-projects" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Projects</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-projects">    
        <li>
    <a class="dropdown-item" href="../starter-analysis-exercise/starter-analysis-exercise.html">
 <span class="dropdown-text">Starter Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../ready-exercise/report.html">
 <span class="dropdown-text">READY Analysis Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../data-exercise/data-exercise.html">
 <span class="dropdown-text">Complex Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../cdcdata-exercise/cdcdata-exercise.html">
 <span class="dropdown-text">CDC Data Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentation-exercise/presentation-exercise.html">
 <span class="dropdown-text">Presentation Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../fitting-exercise/fitting-exercise.html">
 <span class="dropdown-text">Fitting Exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../ml-models-exercise.qmd">
 <span class="dropdown-text">ml-models-exercise</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tidy-tuesday.qmd">
 <span class="dropdown-text">Tidy Tuesday</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/EstherPalmer/EstherPalmer-portfolio"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fitting Exercise</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>First to install packages</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>here() starts at C:/Users/esthe/Documents/GitHub/EstherPalmer-portfolio</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.4.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.12     ✔ rsample      1.3.2 
✔ dials        1.4.3      ✔ tailor       0.1.0 
✔ infer        1.1.0      ✔ tidyr        1.3.2 
✔ modeldata    1.5.1      ✔ tune         2.1.0 
✔ parsnip      1.5.0      ✔ workflows    1.3.0 
✔ purrr        1.2.2      ✔ workflowsets 1.1.1 
✔ recipes      1.3.2      ✔ yardstick    1.4.0 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ purrr::discard() masks scales::discard()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
✖ recipes::step()  masks stats::step()</code></pre>
</div>
</div>
<p>Then to load data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>data_location <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"fitting-exercise"</span>, <span class="st">"Mavoglurant_A2121_nmpk.csv"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(data_location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plotting outcome (DV) as a function of time colored by dose and using ID as a grouping factor</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x=</span>TIME, <span class="at">y=</span>DV, <span class="at">group=</span>ID, <span class="at">color=</span>DOSE)) <span class="sc">+</span> <span class="fu">geom_line</span>()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>remove all OCC=2 entries, keep only OCC=1</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, (OCC <span class="sc">==</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Exclude all Time=0, found sum of DV for each ID, create a new data frame with only time 0 and a new variable Y that contains amount of drug delivered over the whole experiment</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df2, (TIME <span class="sc">!=</span> <span class="dv">0</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>df4 <span class="ot">&lt;-</span> df3 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(ID) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Y =</span> <span class="fu">sum</span>(DV))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>df5 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df2, (TIME <span class="sc">==</span> <span class="dv">0</span>))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>df6 <span class="ot">&lt;-</span> <span class="fu">left_join</span>(<span class="at">x=</span>df5, <span class="at">y=</span>df4, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"ID"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Keep only variables Y, Dose, Age, Sex, Race, WT, HT. Convert Race and Sex to factors</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df7 <span class="ot">&lt;-</span> <span class="fu">select</span>(df6,Y, DOSE, AGE, SEX, RACE, WT, HT)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df7<span class="sc">$</span>SEX <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df7<span class="sc">$</span>SEX)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>df7<span class="sc">$</span>RACE <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df7<span class="sc">$</span>RACE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plots depicting: dose and Y colored by Age Y and weight colored by Sex boxplot of Y by sex boxplot of Y by race</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Y               DOSE            AGE        SEX     RACE   
 Min.   : 826.4   Min.   :25.00   Min.   :18.00   1:104   1 :74  
 1st Qu.:1700.5   1st Qu.:25.00   1st Qu.:26.00   2: 16   2 :36  
 Median :2349.1   Median :37.50   Median :31.00           7 : 2  
 Mean   :2445.4   Mean   :36.46   Mean   :33.00           88: 8  
 3rd Qu.:3050.2   3rd Qu.:50.00   3rd Qu.:40.25                  
 Max.   :5606.6   Max.   :50.00   Max.   :50.00                  
       WT               HT       
 Min.   : 56.60   Min.   :1.520  
 1st Qu.: 73.17   1st Qu.:1.700  
 Median : 82.10   Median :1.770  
 Mean   : 82.55   Mean   :1.759  
 3rd Qu.: 90.10   3rd Qu.:1.813  
 Max.   :115.30   Max.   :1.930  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>DOSE, <span class="at">y=</span>Y, <span class="at">color=</span>AGE)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>WT, <span class="at">y=</span>Y, <span class="at">color=</span>SEX)) <span class="sc">+</span> <span class="fu">geom_point</span>()</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>SEX, <span class="at">y=</span>Y)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p5 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>RACE, <span class="at">y=</span>Y)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>hisDOSE <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>DOSE)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hisDOSE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>hisAGE <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>AGE)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hisAGE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>hisWT <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>WT)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hisWT)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>hisHT <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df7, <span class="fu">aes</span>(<span class="at">x=</span>HT)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(hisHT)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-7-8.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>fit a linear model to Y using Dose and calculate RMSE/R2</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lm_mod1 <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>lm_fit1 <span class="ot">&lt;-</span> lm_mod1 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(Y <span class="sc">~</span> DOSE, <span class="at">data =</span> df7)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>lm_fit1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = Y ~ DOSE, data = data)

Coefficients:
(Intercept)         DOSE  
     323.06        58.21  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>pred1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit1, df7) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(df7)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>met1 <span class="ot">&lt;-</span> <span class="fu">metrics</span>(pred1, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>met1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     666.   
2 rsq     standard       0.516
3 mae     standard     517.   </code></pre>
</div>
</div>
<p>In this model dose has a coefficient of 58 which seems like a high number to me. (whenever my collaborators run models we get numbers like 1.2, although those are probably somewhat different models.) The R2 is .516 which is also decent in my opinion. I still have some issues figuring out how to interpret the RMSE and MAE though.</p>
<p>fit a linear model to Y using all predictors and calculate RMSE/R2</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>lm_mod2 <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>lm_fit2 <span class="ot">&lt;-</span> lm_mod2 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(Y <span class="sc">~</span> DOSE <span class="sc">*</span> AGE <span class="sc">*</span> SEX <span class="sc">*</span> WT <span class="sc">*</span> HT <span class="sc">*</span> RACE, <span class="at">data =</span> df7)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>lm_fit2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = Y ~ DOSE * AGE * SEX * WT * HT * RACE, data = data)

Coefficients:
               (Intercept)                        DOSE  
                 3.737e+05                  -1.280e+04  
                       AGE                        SEX2  
                -1.288e+04                  -3.292e+05  
                        WT                          HT  
                -4.527e+03                  -2.100e+05  
                     RACE2                       RACE7  
                -4.538e+05                  -1.828e+03  
                    RACE88                    DOSE:AGE  
                 5.751e+03                   4.358e+02  
                 DOSE:SEX2                    AGE:SEX2  
                -5.401e+02                   6.850e+03  
                   DOSE:WT                      AGE:WT  
                 1.561e+02                   1.545e+02  
                   SEX2:WT                     DOSE:HT  
                 1.827e+03                   7.201e+03  
                    AGE:HT                     SEX2:HT  
                 7.281e+03                   1.471e+05  
                     WT:HT                  DOSE:RACE2  
                 2.547e+03                   2.147e+04  
                DOSE:RACE7                 DOSE:RACE88  
                 6.996e+01                   1.436e+02  
                 AGE:RACE2                   AGE:RACE7  
                 1.602e+04                          NA  
                AGE:RACE88                  SEX2:RACE2  
                -1.934e+02                   2.501e+04  
                SEX2:RACE7                 SEX2:RACE88  
                        NA                   3.370e+03  
                  WT:RACE2                    WT:RACE7  
                 6.087e+03                          NA  
                 WT:RACE88                    HT:RACE2  
                 3.225e+01                   2.675e+05  
                  HT:RACE7                   HT:RACE88  
                        NA                  -2.314e+03  
             DOSE:AGE:SEX2                 DOSE:AGE:WT  
                -4.216e+01                  -5.229e+00  
              DOSE:SEX2:WT                 AGE:SEX2:WT  
                 2.333e+00                  -1.251e+01  
               DOSE:AGE:HT                DOSE:SEX2:HT  
                -2.446e+02                   1.332e+03  
               AGE:SEX2:HT                  DOSE:WT:HT  
                -2.849e+03                  -8.741e+01  
                 AGE:WT:HT                  SEX2:WT:HT  
                -8.735e+01                  -8.342e+02  
            DOSE:AGE:RACE2              DOSE:AGE:RACE7  
                -7.186e+02                          NA  
           DOSE:AGE:RACE88             DOSE:SEX2:RACE2  
                 2.775e+00                          NA  
           DOSE:SEX2:RACE7            DOSE:SEX2:RACE88  
                        NA                          NA  
            AGE:SEX2:RACE2              AGE:SEX2:RACE7  
                -1.493e+02                          NA  
           AGE:SEX2:RACE88               DOSE:WT:RACE2  
                        NA                  -2.718e+02  
             DOSE:WT:RACE7              DOSE:WT:RACE88  
                        NA                  -2.516e+00  
              AGE:WT:RACE2                AGE:WT:RACE7  
                -2.064e+02                          NA  
             AGE:WT:RACE88               SEX2:WT:RACE2  
                        NA                  -2.356e+02  
             SEX2:WT:RACE7              SEX2:WT:RACE88  
                        NA                          NA  
             DOSE:HT:RACE2               DOSE:HT:RACE7  
                -1.230e+04                          NA  
            DOSE:HT:RACE88                AGE:HT:RACE2  
                        NA                  -9.464e+03  
              AGE:HT:RACE7               AGE:HT:RACE88  
                        NA                          NA  
             SEX2:HT:RACE2               SEX2:HT:RACE7  
                        NA                          NA  
            SEX2:HT:RACE88                 WT:HT:RACE2  
                        NA                  -3.565e+03  
               WT:HT:RACE7                WT:HT:RACE88  
                        NA                          NA  
          DOSE:AGE:SEX2:WT            DOSE:AGE:SEX2:HT  
                        NA                          NA  
            DOSE:AGE:WT:HT             DOSE:SEX2:WT:HT  
                 2.937e+00                          NA  
            AGE:SEX2:WT:HT         DOSE:AGE:SEX2:RACE2  
                        NA                          NA  
       DOSE:AGE:SEX2:RACE7        DOSE:AGE:SEX2:RACE88  
                        NA                          NA  
         DOSE:AGE:WT:RACE2           DOSE:AGE:WT:RACE7  
                 8.881e+00                          NA  
        DOSE:AGE:WT:RACE88          DOSE:SEX2:WT:RACE2  
                        NA                          NA  
        DOSE:SEX2:WT:RACE7         DOSE:SEX2:WT:RACE88  
                        NA                          NA  
         AGE:SEX2:WT:RACE2           AGE:SEX2:WT:RACE7  
                        NA                          NA  
        AGE:SEX2:WT:RACE88           DOSE:AGE:HT:RACE2  
                        NA                   4.143e+02  
         DOSE:AGE:HT:RACE7          DOSE:AGE:HT:RACE88  
                        NA                          NA  
        DOSE:SEX2:HT:RACE2          DOSE:SEX2:HT:RACE7  
                        NA                          NA  
       DOSE:SEX2:HT:RACE88           AGE:SEX2:HT:RACE2  
                        NA                          NA  
         AGE:SEX2:HT:RACE7          AGE:SEX2:HT:RACE88  
                        NA                          NA  
          DOSE:WT:HT:RACE2            DOSE:WT:HT:RACE7  
                 1.552e+02                          NA  
         DOSE:WT:HT:RACE88             AGE:WT:HT:RACE2  
                        NA                   1.214e+02  
           AGE:WT:HT:RACE7            AGE:WT:HT:RACE88  
                        NA                          NA  
          SEX2:WT:HT:RACE2            SEX2:WT:HT:RACE7  
                        NA                          NA  
         SEX2:WT:HT:RACE88         DOSE:AGE:SEX2:WT:HT  
                        NA                          NA  
    DOSE:AGE:SEX2:WT:RACE2      DOSE:AGE:SEX2:WT:RACE7  
                        NA                          NA  
   DOSE:AGE:SEX2:WT:RACE88      DOSE:AGE:SEX2:HT:RACE2  
                        NA                          NA  
    DOSE:AGE:SEX2:HT:RACE7     DOSE:AGE:SEX2:HT:RACE88  
                        NA                          NA  
      DOSE:AGE:WT:HT:RACE2        DOSE:AGE:WT:HT:RACE7  
                -5.107e+00                          NA  
     DOSE:AGE:WT:HT:RACE88       DOSE:SEX2:WT:HT:RACE2  
                        NA                          NA  
     DOSE:SEX2:WT:HT:RACE7      DOSE:SEX2:WT:HT:RACE88  
                        NA                          NA  
      AGE:SEX2:WT:HT:RACE2        AGE:SEX2:WT:HT:RACE7  
                        NA                          NA  
     AGE:SEX2:WT:HT:RACE88   DOSE:AGE:SEX2:WT:HT:RACE2  
                        NA                          NA  
 DOSE:AGE:SEX2:WT:HT:RACE7  DOSE:AGE:SEX2:WT:HT:RACE88  
                        NA                          NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>pred2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit2, df7) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(df7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>met2 <span class="ot">&lt;-</span> <span class="fu">metrics</span>(pred2, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>met2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     475.   
2 rsq     standard       0.754
3 mae     standard     316.   </code></pre>
</div>
</div>
<p>This one has a lower RMSE/MAE and a higher R2, so I can conclude that it is probably a better model than the first.</p>
<p>fit a linear model to SEX using Dose, and one using all predictors, and calculate ROC-AUC</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>lm_mod3 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>()</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>lm_fit3 <span class="ot">&lt;-</span> lm_mod3 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(SEX <span class="sc">~</span> DOSE, <span class="at">data =</span> df7)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>lm_fit3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:  stats::glm(formula = SEX ~ DOSE, family = stats::binomial, data = data)

Coefficients:
(Intercept)         DOSE  
   -0.76482     -0.03175  

Degrees of Freedom: 119 Total (i.e. Null);  118 Residual
Null Deviance:      94.24 
Residual Deviance: 92.43    AIC: 96.43</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pred3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit3, df7, <span class="at">type =</span> <span class="st">"prob"</span>) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(df7)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">roc_auc</span>(pred3, <span class="at">truth =</span> SEX, .pred_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.592</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>lm_mod4 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>()</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>lm_fit4 <span class="ot">&lt;-</span> lm_mod4 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(SEX <span class="sc">~</span> DOSE <span class="sc">*</span> Y <span class="sc">*</span> AGE <span class="sc">*</span> WT <span class="sc">*</span> HT <span class="sc">*</span> RACE, <span class="at">data =</span> df7)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: algorithm did not converge</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>lm_fit4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:  stats::glm(formula = SEX ~ DOSE * Y * AGE * WT * HT * RACE, family = stats::binomial, 
    data = data)

Coefficients:
            (Intercept)                     DOSE                        Y  
             -2.542e+05                4.403e+03                1.393e+02  
                    AGE                       WT                       HT  
              4.504e+03                2.975e+03                1.399e+05  
                  RACE2                    RACE7                   RACE88  
             -3.143e+05                1.896e+02                2.232e+03  
                 DOSE:Y                 DOSE:AGE                    Y:AGE  
             -2.665e+00               -7.289e+01               -2.498e+00  
                DOSE:WT                     Y:WT                   AGE:WT  
             -5.263e+01               -1.629e+00               -5.194e+01  
                DOSE:HT                     Y:HT                   AGE:HT  
             -2.440e+03               -7.638e+01               -2.446e+03  
                  WT:HT               DOSE:RACE2               DOSE:RACE7  
             -1.636e+03                1.232e+04               -6.901e+00  
            DOSE:RACE88                  Y:RACE2                  Y:RACE7  
             -3.023e+00                4.780e+01                       NA  
               Y:RACE88                AGE:RACE2                AGE:RACE7  
             -1.090e+00                2.865e+03                       NA  
             AGE:RACE88                 WT:RACE2                 WT:RACE7  
              9.810e+00                3.732e+03                       NA  
              WT:RACE88                 HT:RACE2                 HT:RACE7  
             -1.189e+01                1.759e+05                       NA  
              HT:RACE88               DOSE:Y:AGE                DOSE:Y:WT  
              6.660e+00                4.723e-02                3.136e-02  
            DOSE:AGE:WT                 Y:AGE:WT                DOSE:Y:HT  
              8.646e-01                2.909e-02                1.466e+00  
            DOSE:AGE:HT                 Y:AGE:HT               DOSE:WT:HT  
              3.993e+01                1.347e+00                2.910e+01  
                Y:WT:HT                AGE:WT:HT             DOSE:Y:RACE2  
              8.932e-01                2.819e+01               -2.156e+00  
           DOSE:Y:RACE7            DOSE:Y:RACE88           DOSE:AGE:RACE2  
                     NA                1.733e-02               -1.321e+01  
         DOSE:AGE:RACE7          DOSE:AGE:RACE88              Y:AGE:RACE2  
                     NA               -5.408e-01               -8.164e-01  
            Y:AGE:RACE7             Y:AGE:RACE88            DOSE:WT:RACE2  
                     NA                       NA               -1.358e+02  
          DOSE:WT:RACE7           DOSE:WT:RACE88               Y:WT:RACE2  
                     NA                       NA               -8.092e-01  
             Y:WT:RACE7              Y:WT:RACE88             AGE:WT:RACE2  
                     NA                       NA               -2.974e+01  
           AGE:WT:RACE7            AGE:WT:RACE88            DOSE:HT:RACE2  
                     NA                       NA               -6.744e+03  
          DOSE:HT:RACE7           DOSE:HT:RACE88               Y:HT:RACE2  
                     NA                       NA               -2.856e+01  
             Y:HT:RACE7              Y:HT:RACE88             AGE:HT:RACE2  
                     NA                       NA               -1.582e+03  
           AGE:HT:RACE7            AGE:HT:RACE88              WT:HT:RACE2  
                     NA                       NA               -2.105e+03  
            WT:HT:RACE7             WT:HT:RACE88            DOSE:Y:AGE:WT  
                     NA                       NA               -5.544e-04  
          DOSE:Y:AGE:HT             DOSE:Y:WT:HT           DOSE:AGE:WT:HT  
             -2.560e-02               -1.725e-02               -4.725e-01  
            Y:AGE:WT:HT         DOSE:Y:AGE:RACE2         DOSE:Y:AGE:RACE7  
             -1.570e-02               -4.927e-03                       NA  
      DOSE:Y:AGE:RACE88          DOSE:Y:WT:RACE2          DOSE:Y:WT:RACE7  
                     NA                2.887e-02                       NA  
       DOSE:Y:WT:RACE88        DOSE:AGE:WT:RACE2        DOSE:AGE:WT:RACE7  
                     NA               -3.548e-01                       NA  
     DOSE:AGE:WT:RACE88           Y:AGE:WT:RACE2           Y:AGE:WT:RACE7  
                     NA                1.611e-02                       NA  
        Y:AGE:WT:RACE88          DOSE:Y:HT:RACE2          DOSE:Y:HT:RACE7  
                     NA                1.209e+00                       NA  
       DOSE:Y:HT:RACE88        DOSE:AGE:HT:RACE2        DOSE:AGE:HT:RACE7  
                     NA                1.901e+00                       NA  
     DOSE:AGE:HT:RACE88           Y:AGE:HT:RACE2           Y:AGE:HT:RACE7  
                     NA                5.061e-01                       NA  
        Y:AGE:HT:RACE88         DOSE:WT:HT:RACE2         DOSE:WT:HT:RACE7  
                     NA                7.479e+01                       NA  
      DOSE:WT:HT:RACE88            Y:WT:HT:RACE2            Y:WT:HT:RACE7  
                     NA                4.804e-01                       NA  
         Y:WT:HT:RACE88          AGE:WT:HT:RACE2          AGE:WT:HT:RACE7  
                     NA                1.689e+01                       NA  
       AGE:WT:HT:RACE88         DOSE:Y:AGE:WT:HT      DOSE:Y:AGE:WT:RACE2  
                     NA                3.006e-04                8.557e-06  
    DOSE:Y:AGE:WT:RACE7     DOSE:Y:AGE:WT:RACE88      DOSE:Y:AGE:HT:RACE2  
                     NA                       NA                2.854e-03  
    DOSE:Y:AGE:HT:RACE7     DOSE:Y:AGE:HT:RACE88       DOSE:Y:WT:HT:RACE2  
                     NA                       NA               -1.639e-02  
     DOSE:Y:WT:HT:RACE7      DOSE:Y:WT:HT:RACE88     DOSE:AGE:WT:HT:RACE2  
                     NA                       NA                2.459e-01  
   DOSE:AGE:WT:HT:RACE7    DOSE:AGE:WT:HT:RACE88        Y:AGE:WT:HT:RACE2  
                     NA                       NA               -9.774e-03  
      Y:AGE:WT:HT:RACE7       Y:AGE:WT:HT:RACE88   DOSE:Y:AGE:WT:HT:RACE2  
                     NA                       NA                       NA  
 DOSE:Y:AGE:WT:HT:RACE7  DOSE:Y:AGE:WT:HT:RACE88  
                     NA                       NA  

Degrees of Freedom: 119 Total (i.e. Null);  47 Residual
Null Deviance:      94.24 
Residual Deviance: 2.864e-09    AIC: 146</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>pred4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit4, df7, <span class="at">type =</span> <span class="st">"prob"</span>) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(df7)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">roc_auc</span>(pred4, <span class="at">truth =</span> SEX, .pred_1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary             1</code></pre>
</div>
</div>
<p>The roc_auc is 1 for the last model which is super interesting. I guess that means that all the data put together are very good at predicting sex. This makes sense given that a lot of the things in the model are correlated with sex (height/weight, and doeses tend to be different for men/women). In model 3, dose alone had an ROC of .6, so it’s probably a decent predictor of sex.</p>
<p>random seed:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>rngseed <span class="ot">=</span> <span class="dv">1234</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>remove race as a variable</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>df8 <span class="ot">&lt;-</span> df7 <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>RACE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>set seed and split data 75:25</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>data_split  <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(df8, <span class="at">prop =</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">4</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">training</span>(data_split)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> <span class="fu">testing</span>(data_split)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>two linear models for Y (continuous outcome of interest) Model 1: dose as only pred Model 2: all predictors</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>lm_mod5 <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>lm_fit5 <span class="ot">&lt;-</span> lm_mod5 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(Y <span class="sc">~</span> DOSE, <span class="at">data =</span> train)</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>lm_fit5</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = Y ~ DOSE, data = data)

Coefficients:
(Intercept)         DOSE  
     535.45        53.42  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>pred5 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit5, train) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(train)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>met5 <span class="ot">&lt;-</span> <span class="fu">metrics</span>(pred5, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>met5</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     703.   
2 rsq     standard       0.451
3 mae     standard     546.   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>lm_mod6 <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>()</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>lm_fit6 <span class="ot">&lt;-</span> lm_mod6 <span class="sc">%&gt;%</span> <span class="fu">fit</span>(Y <span class="sc">~</span> DOSE <span class="sc">*</span> AGE <span class="sc">*</span> SEX <span class="sc">*</span> WT <span class="sc">*</span> HT, <span class="at">data =</span> train)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>lm_fit6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = Y ~ DOSE * AGE * SEX * WT * HT, data = data)

Coefficients:
        (Intercept)                 DOSE                  AGE  
          9.525e+04           -3.070e+03           -1.108e+03  
               SEX2                   WT                   HT  
          1.079e+05           -1.723e+03           -5.049e+04  
           DOSE:AGE            DOSE:SEX2             AGE:SEX2  
          8.184e+01            1.198e+03           -5.065e+03  
            DOSE:WT               AGE:WT              SEX2:WT  
          5.299e+01            3.454e+01            7.704e+02  
            DOSE:HT               AGE:HT              SEX2:HT  
          1.735e+03            5.416e+02           -5.277e+04  
              WT:HT        DOSE:AGE:SEX2          DOSE:AGE:WT  
          9.390e+02            2.381e+01           -1.531e+00  
       DOSE:SEX2:WT          AGE:SEX2:WT          DOSE:AGE:HT  
          2.727e+01           -1.869e+01           -4.453e+01  
       DOSE:SEX2:HT          AGE:SEX2:HT           DOSE:WT:HT  
         -2.680e+03            3.534e+03           -2.963e+01  
          AGE:WT:HT           SEX2:WT:HT     DOSE:AGE:SEX2:WT  
         -1.861e+01           -3.898e+02                   NA  
   DOSE:AGE:SEX2:HT       DOSE:AGE:WT:HT      DOSE:SEX2:WT:HT  
                 NA            8.471e-01                   NA  
     AGE:SEX2:WT:HT  DOSE:AGE:SEX2:WT:HT  
                 NA                   NA  </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>pred6 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit6, train) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>met6 <span class="ot">&lt;-</span> <span class="fu">metrics</span>(pred6, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>met6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard     578.   
2 rsq     standard       0.628
3 mae     standard     415.   </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>NM <span class="ot">&lt;-</span> <span class="fu">null_model</span>(<span class="at">mode =</span> <span class="st">"regression"</span>, <span class="at">engine =</span> <span class="st">"parsnip"</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>NM_fit <span class="ot">&lt;-</span> NM <span class="sc">%&gt;%</span> <span class="fu">fit</span>(Y <span class="sc">~</span>., <span class="at">data =</span> train)</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>NM_fit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object

Null Classification Model
Predicted Value: 2509.171 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>pred7 <span class="ot">&lt;-</span> <span class="fu">predict</span>(NM_fit, train) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(train)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>met7 <span class="ot">&lt;-</span> <span class="fu">rmse</span>(pred7, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>met7</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        948.</code></pre>
</div>
</div>
<p>I set the random seed correctly, however my values are different from the ones we’re supposed to get. I got 948 for the null which is correct, 703 for model 1 (correct value 702), and 578 for model 2 (correct value 627). This does mean that model 2 is currently performing best as it has the lowest rmse</p>
<p>Now I need to do a 10-fold CV</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train, <span class="at">v =</span> <span class="dv">10</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>folds</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#  10-fold cross-validation 
# A tibble: 10 × 2
   splits         id    
   &lt;list&gt;         &lt;chr&gt; 
 1 &lt;split [81/9]&gt; Fold01
 2 &lt;split [81/9]&gt; Fold02
 3 &lt;split [81/9]&gt; Fold03
 4 &lt;split [81/9]&gt; Fold04
 5 &lt;split [81/9]&gt; Fold05
 6 &lt;split [81/9]&gt; Fold06
 7 &lt;split [81/9]&gt; Fold07
 8 &lt;split [81/9]&gt; Fold08
 9 &lt;split [81/9]&gt; Fold09
10 &lt;split [81/9]&gt; Fold10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>lm_wf1 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod5) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> DOSE)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>lm_fit_cv1 <span class="ot">&lt;-</span> lm_wf1 <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>lm_fit_cv1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(lm_fit_cv1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator    mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   691.       10 67.5    pre0_mod0_post0
2 rsq     standard     0.512    10  0.0592 pre0_mod0_post0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>lm_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod5) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> DOSE <span class="sc">*</span> AGE <span class="sc">*</span> SEX <span class="sc">*</span> WT <span class="sc">*</span> HT)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>lm_fit_cv2 <span class="ot">&lt;-</span> lm_wf2 <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: prediction from rank-deficient fit; consider predict(., rankdeficient="NA")</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x10</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>lm_fit_cv2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;

There were issues with some computations:

  - Warning(s) x10: prediction from rank-deficient fit; consider predict(., rankdefic...

Run `show_notes(.Last.tune.result)` for more information.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(lm_fit_cv2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n   std_err .config        
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   7599.       10 5695.     pre0_mod0_post0
2 rsq     standard      0.347    10    0.0807 pre0_mod0_post0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>NM_wf <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(NM) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> .)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>NM_fit_cv <span class="ot">&lt;-</span> NM_wf <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: A correlation computation is required, but `estimate` is constant and has 0
               standard deviation, resulting in a divide by 0 error. `NA` will be returned.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>NM_fit_cv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;

There were issues with some computations:

  - Warning(s) x10: A correlation computation is required, but `estimate` is constant...

Run `show_notes(.Last.tune.result)` for more information.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(NM_fit_cv)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator  mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard    933.    10    76.7 pre0_mod0_post0
2 rsq     standard    NaN      0    NA   pre0_mod0_post0</code></pre>
</div>
</div>
<p>Well the rmse for the null model was similar but different at 943, SE at 66.2. RMSE for the second model with the full formula was much worse at 2003, while rmse for the Y~DOSE model was 687.</p>
<p>Now I need a different random seed</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">347</span>)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>folds2 <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(train, <span class="at">v =</span> <span class="dv">10</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>folds2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#  10-fold cross-validation 
# A tibble: 10 × 2
   splits         id    
   &lt;list&gt;         &lt;chr&gt; 
 1 &lt;split [81/9]&gt; Fold01
 2 &lt;split [81/9]&gt; Fold02
 3 &lt;split [81/9]&gt; Fold03
 4 &lt;split [81/9]&gt; Fold04
 5 &lt;split [81/9]&gt; Fold05
 6 &lt;split [81/9]&gt; Fold06
 7 &lt;split [81/9]&gt; Fold07
 8 &lt;split [81/9]&gt; Fold08
 9 &lt;split [81/9]&gt; Fold09
10 &lt;split [81/9]&gt; Fold10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>lm_wf3 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod5) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> DOSE)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>lm_fit_cv3 <span class="ot">&lt;-</span> lm_wf3 <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds2)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>lm_fit_cv3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 4]&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(lm_fit_cv3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator    mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   684.       10 67.4    pre0_mod0_post0
2 rsq     standard     0.504    10  0.0722 pre0_mod0_post0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>lm_wf4 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(lm_mod5) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> DOSE <span class="sc">*</span> AGE <span class="sc">*</span> SEX <span class="sc">*</span> WT <span class="sc">*</span> HT)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>lm_fit_cv4 <span class="ot">&lt;-</span> lm_wf4 <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: prediction from rank-deficient fit; consider predict(., rankdeficient="NA")</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>There were issues with some computations   A: x10</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>lm_fit_cv4</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;

There were issues with some computations:

  - Warning(s) x10: prediction from rank-deficient fit; consider predict(., rankdefic...

Run `show_notes(.Last.tune.result)` for more information.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(lm_fit_cv2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator     mean     n   std_err .config        
  &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard   7599.       10 5695.     pre0_mod0_post0
2 rsq     standard      0.347    10    0.0807 pre0_mod0_post0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a>NM_wf2 <span class="ot">&lt;-</span> <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> <span class="fu">add_model</span>(NM) <span class="sc">%&gt;%</span> <span class="fu">add_formula</span>(Y <span class="sc">~</span> .)</span>
<span id="cb104-2"><a href="#cb104-2" aria-hidden="true" tabindex="-1"></a>NM_fit_cv2 <span class="ot">&lt;-</span> NM_wf2 <span class="sc">%&gt;%</span> <span class="fu">fit_resamples</span>(folds2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>→ A | warning: A correlation computation is required, but `estimate` is constant and has 0
               standard deviation, resulting in a divide by 0 error. `NA` will be returned.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>NM_fit_cv2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Resampling results
# 10-fold cross-validation 
# A tibble: 10 × 4
   splits         id     .metrics         .notes          
   &lt;list&gt;         &lt;chr&gt;  &lt;list&gt;           &lt;list&gt;          
 1 &lt;split [81/9]&gt; Fold01 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 2 &lt;split [81/9]&gt; Fold02 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 3 &lt;split [81/9]&gt; Fold03 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 4 &lt;split [81/9]&gt; Fold04 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 5 &lt;split [81/9]&gt; Fold05 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 6 &lt;split [81/9]&gt; Fold06 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 7 &lt;split [81/9]&gt; Fold07 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 8 &lt;split [81/9]&gt; Fold08 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
 9 &lt;split [81/9]&gt; Fold09 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;
10 &lt;split [81/9]&gt; Fold10 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 4]&gt;

There were issues with some computations:

  - Warning(s) x10: A correlation computation is required, but `estimate` is constant...

Run `show_notes(.Last.tune.result)` for more information.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb108"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" aria-hidden="true" tabindex="-1"></a><span class="fu">collect_metrics</span>(NM_fit_cv2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  .metric .estimator  mean     n std_err .config        
  &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;          
1 rmse    standard    938.    10    56.2 pre0_mod0_post0
2 rsq     standard    NaN      0    NA   pre0_mod0_post0</code></pre>
</div>
</div>
<p>Null model is now at 938, similar but slightly different second model is still at 2003 First model is now at 684. Similar, but slightly different to the other random seed.</p>
<section id="this-section-added-by-rebecca-basta" class="level1">
<h1>This section added by Rebecca Basta</h1>
</section>
<section id="null-model-predictions" class="level1">
<h1>Null Model Predictions</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a>plot_null <span class="ot">&lt;-</span> <span class="fu">predict</span>(NM_fit, train) <span class="sc">%&gt;%</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(train <span class="sc">%&gt;%</span> <span class="fu">select</span>(Y)) <span class="sc">%&gt;%</span></span>
<span id="cb110-3"><a href="#cb110-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Null model"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="dose-model-predictions" class="level1">
<h1>Dose Model Predictions</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>plot_mod1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit5, train) <span class="sc">%&gt;%</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(train <span class="sc">%&gt;%</span> <span class="fu">select</span>(Y)) <span class="sc">%&gt;%</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"Dose only"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="all-predictor-model-predictions" class="level1">
<h1>All Predictor Model Predictions</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>plot_mod2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit6, train) <span class="sc">%&gt;%</span></span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(train <span class="sc">%&gt;%</span> <span class="fu">select</span>(Y)) <span class="sc">%&gt;%</span></span>
<span id="cb112-3"><a href="#cb112-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">model =</span> <span class="st">"All predictors"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
</div>
</section>
<section id="combine-into-one-dataframe" class="level1">
<h1>Combine into One Dataframe</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(plot_null, plot_mod1, plot_mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="predicted-vs-observed-plot" class="level1">
<h1>Predicted vs Observed Plot</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a>p_pred_obs <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(plot_df, <span class="fu">aes</span>(<span class="at">x =</span> Y, <span class="at">y =</span> .pred, <span class="at">color =</span> model, <span class="at">shape =</span> model)) <span class="sc">+</span></span>
<span id="cb115-2"><a href="#cb115-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb115-3"><a href="#cb115-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb115-4"><a href="#cb115-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5000</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5000</span>)) <span class="sc">+</span></span>
<span id="cb115-5"><a href="#cb115-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb115-6"><a href="#cb115-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Observed values"</span>,</span>
<span id="cb115-7"><a href="#cb115-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted values"</span>,</span>
<span id="cb115-8"><a href="#cb115-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted vs observed values for 3 training-set models"</span></span>
<span id="cb115-9"><a href="#cb115-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb115-10"><a href="#cb115-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb115-11"><a href="#cb115-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb115-12"><a href="#cb115-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p_pred_obs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The model that uses dosee as the only predictor, the predicted values fall along three horizontal lines becuase thedose cariable takes three values.</p>
</section>
<section id="plot-with-model-using-all-predictors" class="level1">
<h1>Plot with Model Using All Predictors</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a>resid_df <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit6, train) <span class="sc">%&gt;%</span></span>
<span id="cb116-2"><a href="#cb116-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(train <span class="sc">%&gt;%</span> <span class="fu">select</span>(Y)) <span class="sc">%&gt;%</span></span>
<span id="cb116-3"><a href="#cb116-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">residual =</span> .pred <span class="sc">-</span> Y)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>p_resid <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resid_df, <span class="fu">aes</span>(<span class="at">x =</span> .pred, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb118-3"><a href="#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb118-4"><a href="#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">2000</span>, <span class="dv">2000</span>)) <span class="sc">+</span></span>
<span id="cb118-5"><a href="#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb118-6"><a href="#cb118-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Predicted values"</span>,</span>
<span id="cb118-7"><a href="#cb118-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Residuals (predicted - observed)"</span>,</span>
<span id="cb118-8"><a href="#cb118-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Predicted values vs residuals for model 2"</span></span>
<span id="cb118-9"><a href="#cb118-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb118-10"><a href="#cb118-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb118-11"><a href="#cb118-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb118-12"><a href="#cb118-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(p_resid)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-predictions-and-uncertainty" class="level1">
<h1>Model Predictions and Uncertainty</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb119-2"><a href="#cb119-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(rngseed)</span>
<span id="cb119-3"><a href="#cb119-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb119-4"><a href="#cb119-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 100 bootstrap resamples</span></span>
<span id="cb119-5"><a href="#cb119-5" aria-hidden="true" tabindex="-1"></a>dat_bs <span class="ot">&lt;-</span> <span class="fu">bootstraps</span>(train, <span class="at">times =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store predictions</span></span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(train)</span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>pred_bs <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="cn">NA</span>, <span class="at">nrow =</span> B, <span class="at">ncol =</span> n)</span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through bootstrap samples</span></span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>B) {</span>
<span id="cb120-8"><a href="#cb120-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb120-9"><a href="#cb120-9" aria-hidden="true" tabindex="-1"></a>  dat_sample <span class="ot">&lt;-</span> rsample<span class="sc">::</span><span class="fu">analysis</span>(dat_bs<span class="sc">$</span>splits[[i]])</span>
<span id="cb120-10"><a href="#cb120-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb120-11"><a href="#cb120-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model on bootstrap sample</span></span>
<span id="cb120-12"><a href="#cb120-12" aria-hidden="true" tabindex="-1"></a>  fit_bs <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> DOSE <span class="sc">*</span> AGE <span class="sc">*</span> SEX <span class="sc">*</span> WT <span class="sc">*</span> HT, <span class="at">data =</span> dat_sample)</span>
<span id="cb120-13"><a href="#cb120-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb120-14"><a href="#cb120-14" aria-hidden="true" tabindex="-1"></a><span class="co"># predict on original training data</span></span>
<span id="cb120-15"><a href="#cb120-15" aria-hidden="true" tabindex="-1"></a>  pred_bs[i, ] <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_bs, <span class="at">newdata =</span> train)</span>
<span id="cb120-16"><a href="#cb120-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases
Warning in predict.lm(fit_bs, newdata = train): prediction from rank-deficient
fit; attr(*, "non-estim") has doubtful cases</code></pre>
</div>
</div>
</section>
<section id="compute-median-and-89-confidence-intervals" class="level1">
<h1>4. Compute Median and 89% Confidence Intervals</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>preds <span class="ot">&lt;-</span> pred_bs <span class="sc">|&gt;</span> <span class="fu">apply</span>(<span class="dv">2</span>, quantile, <span class="fu">c</span>(<span class="fl">0.055</span>, <span class="fl">0.5</span>, <span class="fl">0.945</span>)) <span class="sc">|&gt;</span> <span class="fu">t</span>()</span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Original predictions</span></span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>orig_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit6, train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Put in dataframe</span></span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>boot_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">observed =</span> train<span class="sc">$</span>Y,</span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_mean =</span> orig_pred,</span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_lower =</span> preds[,<span class="dv">1</span>],</span>
<span id="cb124-6"><a href="#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_median =</span> preds[,<span class="dv">2</span>],</span>
<span id="cb124-7"><a href="#cb124-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">pred_upper =</span> preds[,<span class="dv">3</span>]</span>
<span id="cb124-8"><a href="#cb124-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plot-predicted-vs-observed-with-uncertainty" class="level1">
<h1>Plot Predicted vs Observed with Uncertainty</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> boot_df, <span class="fu">aes</span>(<span class="at">x =</span> observed, <span class="at">y =</span> .pred), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> boot_df, <span class="fu">aes</span>(<span class="at">x =</span> observed, <span class="at">y =</span> pred_median), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(</span>
<span id="cb125-5"><a href="#cb125-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> boot_df,</span>
<span id="cb125-6"><a href="#cb125-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> observed, <span class="at">ymin =</span> pred_lower, <span class="at">ymax =</span> pred_upper),</span>
<span id="cb125-7"><a href="#cb125-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb125-8"><a href="#cb125-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.5</span></span>
<span id="cb125-9"><a href="#cb125-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb125-10"><a href="#cb125-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="dv">1</span>, <span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb125-11"><a href="#cb125-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5000</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">5000</span>)) <span class="sc">+</span></span>
<span id="cb125-12"><a href="#cb125-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb125-13"><a href="#cb125-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Observed values"</span>,</span>
<span id="cb125-14"><a href="#cb125-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted values"</span>,</span>
<span id="cb125-15"><a href="#cb125-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Bootstrap predictions with 89% confidence intervals"</span></span>
<span id="cb125-16"><a href="#cb125-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb125-17"><a href="#cb125-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The black points represent the original model predictions, and most of the points lie close to the 45° line, this indicates that there is not much variability between observed and predicted values. The blue points represent the median predictions from the bootstrap samples, they overlap with the original predictions. This overlap shows that the model is consistent across resampled datasets. The red vertical lines indicate the 89% confidence intervals, which are small for most individuals demonstrating low uncertainty, but are bigger for a few individuals. The pattern shows that the model represents most of trends in the data, and the bootstrap confirms the consistency and uncertainty of the predictions.</p>
</section>
<section id="part-3" class="level1">
<h1>Part 3</h1>
<p>Use model 2 on test data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>final_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_fit6, test) <span class="sc">%&gt;%</span> <span class="fu">bind_cols</span>(test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in predict.lm(object = object$fit, newdata = new_data, type =
"response", : prediction from rank-deficient fit; consider predict(.,
rankdeficient="NA")</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a>met_final <span class="ot">&lt;-</span> <span class="fu">metrics</span>(final_pred, <span class="at">truth =</span> Y, <span class="at">estimate =</span> .pred)</span>
<span id="cb128-2"><a href="#cb128-2" aria-hidden="true" tabindex="-1"></a>met_final</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard   2768.    
2 rsq     standard      0.0482
3 mae     standard   1213.    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>df7billion <span class="ot">&lt;-</span> <span class="fu">merge</span>(final_pred, pred6, <span class="at">by=</span><span class="st">"Y"</span>)</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a>final_plot <span class="ot">&lt;-</span> df7billion <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Y)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>.pred.x, <span class="at">color=</span><span class="st">"blue"</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y=</span>.pred.y, <span class="at">color=</span><span class="st">"green"</span>))</span>
<span id="cb130-4"><a href="#cb130-4" aria-hidden="true" tabindex="-1"></a>final_plot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="fitting-exercise_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Save clean data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>save_data_location <span class="ot">&lt;-</span> here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"ml-models-exercise"</span>,<span class="st">"clean.rds"</span>)</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">saveRDS</span>(df7, <span class="at">file =</span> save_data_location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>